version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
install:
  # force to use msbuild 15.0 the path as VS2013 solutions uses msbuild 12.0 
  - cmd: set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
build:
  project: spice-sample-pos\spice-sample-pos.sln
before_build:
  # restore nuget
  - nuget restore spice-samplepos\spice-sample-pos.sln
